---
title: "Healthcare work force shortage and the burden of HIV in sub-Saharan Africa"
author: "MHD Nour Audi"
date: "11/8/2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
  
```

```{r}
# open needed libraries 
library(readxl)
library(tidyverse)
library(ggpubr)
library(corrplot)
library(stargazer)

```

```{r}
# importing data 

GBD_HIV <- read_excel("/Users/battou/Documents/MPH Brown /2018 Fall PHP 1100/Data analysis/project/PHP 1100/data/Book2.xlsx", 
                      sheet = "Sheet2", col_types = c("numeric", 
                                                      "text", "numeric", "text", "blank", 
                                                      "blank", "blank", "blank", "blank", 
                                                      "text", "blank", "text", "numeric", 
                                                      "numeric", "numeric", "numeric"))
# importing health work force data
health_work_force <- read_excel("/Users/battou/Documents/MPH Brown /2018 Fall PHP 1100/Data analysis/project/data/Book2.xlsx", 
                                sheet = "Sheet1")
names(health_work_force )[1] <- c("location_name")

#importing ART treatment data 
ARTcov <- read_excel("/Users/battou/Documents/MPH Brown /2018 Fall PHP 1100/Data analysis/project/PHP 1100/data/HIV_0000000009,HIV_0000000010,HIV_0000000001,HIV_ARTCOVERAGE.xlsx", 
                     sheet = "Sheet9", col_types = c("blank", 
                                                     "text", "numeric", "numeric", "numeric"))
names(ARTcov)[1] <- c("location_name")

# imprting shortage
shortage <- read_excel("/Users/battou/Documents/MPH Brown /2018 Fall PHP 1100/Data analysis/project/data/Book2.xlsx", 
                       sheet = "shortage")
names(shortage)[1] <- c("location_name")
names(shortage)[2] <- c("doctors_shortage")
names(shortage)[3] <- c("nurses_midwives_shortage")
names(shortage)[4] <- c("total_shortage")
names(shortage)[5] <- c("doctors_equivalents_shortage")

```

```{r}
# merging and cleaning data

merged <- left_join( x = GBD_HIV, y = health_work_force, by = "location_name" )
merged_clean <- merged[complete.cases(merged),]
names(merged_clean)[12] <- c("Nurses_midwives")
names(merged_clean)[14] <- c("Doctors_equivalents")

merged_clean2 <- left_join(merged_clean, ARTcov, by = "location_name")
names(merged_clean2)[18] <- c("coverage")
colnames(merged_clean2)

# final merge with shortage data
merged_final <- left_join(x = merged_clean2 , y = shortage , by = "location_name")
```
```{r}
# descriptive analysis 
merged_clean3 <- merged_clean2  %>%
   select(location_id, measure_name, val,Doctors,Nurses_midwives, Total, coverage) %>%
  spread(key = measure_name, val) %>%
 left_join(  y = merged_clean2[,3:4], by = "location_id") %>%
   filter (! duplicated(location_id))

graph1 <- ggplot(merged_clean3, aes(x = Nurses_midwives, y =  coverage , label = location_name)) +
  geom_point() +
  geom_text(size = 3, check_overlap = TRUE, hjust = 0.1, nudge_x = 0.5)
graph1


merged_final2 <-  merged_final %>%
   select(location_id, measure_name, val,Doctors,Nurses_midwives, Total,Doctors_equivalents, coverage, doctors_shortage,  nurses_midwives_shortage, total_shortage, doctors_equivalents_shortage) %>%
  spread(key = measure_name, val)  %>%
 left_join(  y = merged_clean2[,3:4], by = "location_id") %>%
   filter (! duplicated(location_id))
names(merged_final2)[11] <- c("DALYs")

  
graph2 <- ggplot(merged_final2, aes(x = nurses_midwives_shortage , y =  Deaths , label = location_name)) +
  geom_point() +
  geom_text(size = 3, check_overlap = F, hjust = 0.1, nudge_x = 0.05)
graph2


```


```{r}
# correlation matrix 
merged_corr <- merged_clean %>%
  select(location_id, measure_name, val,Doctors,Nurses_midwives, Total, Doctors_equivalents) %>%
  spread(key = measure_name, val) 
 
correlation_matrix <- round( cor(merged_corr), 3)



merged_corr2 <- merged_clean2  %>%
   select(location_id, measure_name, val,Doctors,Nurses_midwives, Total, coverage) %>%
  spread(key = measure_name, val) %>%
  filter( !is.na(coverage))

# final correlation after excluding NA rows 
merged_final2_corr <- merged_final2[1:13]
merged_final2_corr <- merged_final2_corr[complete.cases(merged_final2_corr), ]
 
merged_final2_corr_matrix <- round(cor(merged_final2_corr), 3)

#  export to csv
write_csv(merged_final2_corr, path = "/Users/battou/Documents/MPH Brown /2018 Fall PHP 1100/Data analysis/project/data/results.csv")

write_csv( as.data.frame( merged_final2_corr_matrix), path = "/Users/battou/Documents/MPH Brown /2018 Fall PHP 1100/Data analysis/project/data/results2.csv")

write_csv(as.data.frame( p.mat3), path = "/Users/battou/Documents/MPH Brown /2018 Fall PHP 1100/Data analysis/project/data/results3.csv")

correlation_matrix2 <- round( cor(merged_corr2), 3)

```

```{r}

# function to calculate P value

cor.mtest <- function(mat, ...) {
    mat <- as.matrix(mat)
    n <- ncol(mat)
    p.mat<- matrix(NA, n, n)
    diag(p.mat) <- 0
    for (i in 1:(n - 1)) {
        for (j in (i + 1):n) {
            tmp <- cor.test(mat[, i], mat[, j], ...)
            p.mat[i, j] <- p.mat[j, i] <- tmp$p.value
        }
    }
    colnames(p.mat) <- rownames(p.mat) <- colnames(mat)
    p.mat
}


# P-value matrix  
 p.mat <- cor.mtest(merged_corr)
 p.mat2 <- cor.mtest(merged_corr2)
 p.mat3 <- cor.mtest(merged_final2_corr)
 
# visualise correlation 
 corrplot(corr = correlation_matrix, type = "full" ,
          tl.col="black", tl.srt=45,
          p.mat = p.mat, sig.level = 0.05, insig = "blank" )
 
 corrplot(corr = correlation_matrix2, type = "upper" ,
          tl.col="black", tl.srt=45, tl.cex = 1,
          p.mat = p.mat2, sig.level = 0.05, insig = "blank" )
 
 corrplot(corr = merged_final2_corr_matrix, type = "upper" ,method = "square",
          tl.col="black", tl.srt=45, tl.cex = 1,
          p.mat = p.mat3, sig.level = 0.05)
```

```{r}

# best fit scatter plot
 scatter_nurs_vs_mort <-  merged_clean %>%
   filter(measure_name == "Deaths") %>%
   ggscatter( x = "Nurses_midwives", y = "val",
              add = "reg.line", conf.int = TRUE, 
              cor.coef = TRUE, cor.method = "pearson",
              xlab =  "Estimated Nurses & midwives Density per 1000", ylab = "HIV Mortality rate per 100 0000")

 scatter_nurs_vs_cov <-  merged_clean2 %>%
   filter(measure_name == "Deaths") %>%
   ggscatter( x = "Nurses_midwives", y = "coverage",
              add = "reg.line", conf.int = TRUE, 
              cor.coef = TRUE, cor.method = "pearson",
              xlab =  "Estimated Nurses & midwives Density per 1000", ylab = "ART coverage %")
 
 scatter_docshort_cov <- merged_final2 %>%
   mutate(doctors_shortage_seq = (doctors_shortage *10)^2) %>%
   ggscatter( x = "doctors_shortage_seq", y = "DALYs" , 
              add = "reg.line", conf.int = TRUE, 
              cor.coef = TRUE, cor.method = "pearson",
              xlab =  "Estimated Doctors Shortage as Density per 10 000 population", ylab = "number of DALYs") +
   geom_point() +
   geom_text(label = merged_final2$location_name, size = 3, check_overlap = TRUE, hjust = 0.1, nudge_x = 0.5)
 scatter_docshort_cov
 

# correlation test
cor.test(merged_corr$Nurses_midwives, merged_corr$Deaths)

# linear model  
 lm <- lm( Deaths ~ Nurses_midwives
             , data = merged_final2 )
 summary(lm)
 
 
# regress quadratic function of doctors shortage 
 merged_final3 <- merged_final2 %>%
   mutate(doctors_shortage2 = (doctors_shortage)^2)
 
 lm_shortage <- lm(DALYs ~  doctors_shortage, data = na.omit( merged_final3))
 prid <- predict(lm_shortage)

 lm_shortage2 <- lm(DALYs ~  doctors_shortage2, data = na.omit( merged_final3))
 prid2 <- predict(lm_shortage2)
 summary(lm_shortage2)
 


stargazer(lm_shortage , type = "text")

```
